import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import '../models/product.dart';
import '../services/api_service.dart';
import '../widgets/decimal_input_field.dart';

class ManualProductFormScreen extends StatefulWidget {
  final String? initialName;
  final double? initialBuyPrice;
  final Product? existingProduct; // For editing existing product

  const ManualProductFormScreen({
    super.key,
    this.initialName,
    this.initialBuyPrice,
    this.existingProduct,
  });

  @override
  State<ManualProductFormScreen> createState() => _ManualProductFormScreenState();
}

class _ManualProductFormScreenState extends State<ManualProductFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _buyPriceController = TextEditingController();
  final _profitMarginController = TextEditingController(text: '40');

  @override
  void initState() {
    super.initState();

    // Eğer düzenleme modundaysa (existingProduct varsa), onu yükle
    if (widget.existingProduct != null) {
      _nameController.text = widget.existingProduct!.name;
      _buyPriceController.text = widget.existingProduct!.buyPriceExcludingVat.toString();
      _profitMarginController.text = widget.existingProduct!.marginPercentage.toString();
      _selectedVatRate = widget.existingProduct!.vatRate;
    }
    // Değilse initial değerler varsa onları yükle
    else {
      if (widget.initialName != null) {
        _nameController.text = widget.initialName!;
      }
      if (widget.initialBuyPrice != null) {
        _buyPriceController.text = widget.initialBuyPrice.toString();
      }
    }
  }

  double _selectedVatRate = 20.0;
  bool _isLoading = false;

  final ApiService _apiService = ApiService();

  @override
  void dispose() {
    _nameController.dispose();
    _buyPriceController.dispose();
    _profitMarginController.dispose();
    super.dispose();
  }

  Future<void> _saveProduct() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final product = Product(
        id: widget.existingProduct?.id ?? 0,
        productCode: widget.existingProduct?.productCode ?? '', // Will be generated by backend for new products
        name: _nameController.text.trim(),
        listPrice: 0,
        buyPriceExcludingVat: double.parse(_buyPriceController.text),
        buyPriceIncludingVat: 0,
        myPrice: 0,
        discount1: 0,
        discount2: 0,
        discount3: 0,
        vatRate: _selectedVatRate,
        marginPercentage: double.parse(_profitMarginController.text),
        lastUpdated: DateTime.now(),
        isManual: true,
      );

      final savedProduct = widget.existingProduct != null
          ? await _apiService.updateManualProduct(product)
          : await _apiService.createManualProduct(product);

      if (mounted) {
        // Oluşturulan/Güncellenen ürünü geri döndür (teklif formuna eklenebilsin)
        Navigator.pop(context, savedProduct);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(widget.existingProduct != null
                ? 'Manuel ürün başarıyla güncellendi'
                : 'Manuel ürün başarıyla eklendi'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        if (kDebugMode) {
          print('🔴 UI ERROR CAUGHT: $e');
        }
        String errorMessage = 'Hata: $e';

        // Duplicate ürün hatası kontrolü (409 Conflict)
        final errorStr = e.toString().toLowerCase();
        if (kDebugMode) {
          print('🔍 Error string (lowercase): $errorStr');
        }

        if (errorStr.contains('409') ||
            errorStr.contains('conflict') ||
            errorStr.contains('zaten mevcut') ||
            errorStr.contains('already exists')) {
          if (kDebugMode) {
            print('✅ DUPLICATE DETECTED IN UI');
          }
          errorMessage = 'Bu isimde bir ürün zaten mevcut!\n\nLütfen farklı bir ürün adı kullanın.';
        } else if (errorStr.contains('400') || errorStr.contains('bad request')) {
          if (kDebugMode) {
            print('⚠️ BAD REQUEST DETECTED');
          }
          errorMessage = 'Geçersiz veri girişi. Lütfen tüm alanları kontrol edin.';
        } else if (errorStr.contains('500') || errorStr.contains('internal server')) {
          if (kDebugMode) {
            print('⚠️ SERVER ERROR DETECTED');
          }
          errorMessage = 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.';
        } else if (errorStr.contains('network') || errorStr.contains('socket')) {
          if (kDebugMode) {
            print('⚠️ NETWORK ERROR DETECTED');
          }
          errorMessage = 'Bağlantı hatası. İnternet bağlantınızı kontrol edin.';
        }

        if (kDebugMode) {
          print('📤 SHOWING ERROR MESSAGE: $errorMessage');
        }

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(errorMessage),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 5),
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _deleteProduct() async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Ürünü Sil'),
        content: Text('${widget.existingProduct!.name} ürününü silmek istediğinizden emin misiniz?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('İptal'),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Sil'),
          ),
        ],
      ),
    );

    if (confirmed != true) return;

    setState(() => _isLoading = true);

    try {
      await _apiService.deleteManualProduct(widget.existingProduct!.id);

      if (mounted) {
        Navigator.pop(context, 'deleted'); // Return 'deleted' to indicate deletion
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Manuel ürün başarıyla silindi'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoading = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Silme hatası: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.existingProduct != null ? 'Manuel Ürün Düzenle' : 'Manuel Ürün Ekle'),
        actions: widget.existingProduct != null
            ? [
                IconButton(
                  icon: const Icon(Icons.delete),
                  tooltip: 'Ürünü Sil',
                  onPressed: () => _deleteProduct(),
                ),
              ]
            : null,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    TextFormField(
                      controller: _nameController,
                      decoration: const InputDecoration(
                        labelText: 'Ürün Adı',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Ürün adı gerekli';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    DecimalInputField(
                      controller: _buyPriceController,
                      labelText: 'Alış Fiyatı (KDV Hariç)',
                      suffixText: '₺',
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Alış fiyatı gerekli';
                        }
                        final price = double.tryParse(value);
                        if (price == null || price <= 0) {
                          return 'Geçerli bir fiyat girin';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    DecimalInputWithStepper(
                      controller: _profitMarginController,
                      labelText: 'Kar Marjı',
                      suffixText: '%',
                      step: 10,
                      min: 0,
                      max: 1000,
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Kar marjı gerekli';
                        }
                        final margin = double.tryParse(value);
                        if (margin == null || margin < 0) {
                          return 'Geçerli bir değer girin';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 16),
                    DropdownButtonFormField<double>(
                      value: _selectedVatRate,
                      decoration: const InputDecoration(
                        labelText: 'KDV Oranı',
                        border: OutlineInputBorder(),
                      ),
                      items: const [
                        DropdownMenuItem(value: 10.0, child: Text('%10')),
                        DropdownMenuItem(value: 20.0, child: Text('%20')),
                      ],
                      onChanged: (value) {
                        if (value != null) {
                          setState(() => _selectedVatRate = value);
                        }
                      },
                    ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: _saveProduct,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.all(16),
                      ),
                      child: const Text('Kaydet'),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
